server:
  port: 0
  address: localhost

spring:
  application:
    name: my-first-service
  cloud:
    config:
      uri: http://localhost:8888
      name: ecommerce

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${random.value}


